### ISSUE TITLE
Wifi scan throws an error

### ISSUE THREAD

**Issue by gdaybrice** [resin-io-playground/resin-cam#4]
Cloned and push the repo on my rpi3 and I keep getting an error. Any ideas?

```
04.07.17 12:03:55 (+1000) Systemd init system enabled.
04.07.17 12:03:55 (+1000) systemd 215 running in system mode. (+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP
 +GCRYPT +ACL +XZ -SECCOMP -APPARMOR)
04.07.17 12:03:55 (+1000) Detected virtualization 'other'.
04.07.17 12:03:55 (+1000) Detected architecture 'arm'.
04.07.17 12:03:55 (+1000) Set hostname to <7ccbb40>.
04.07.17 12:04:04 (+1000) Unhandled rejection Error: Command failed: iw wlan0 scan ap-force
04.07.17 12:04:04 (+1000)
04.07.17 12:04:04 (+1000)     at ChildProcess.exithandler (child_process.js:204:12)
04.07.17 12:04:04 (+1000)     at emitTwo (events.js:106:13)
04.07.17 12:04:04 (+1000)     at ChildProcess.emit (events.js:191:7)
04.07.17 12:04:04 (+1000)     at maybeClose (internal/child_process.js:886:16)
04.07.17 12:04:04 (+1000)     at Socket.<anonymous> (internal/child_process.js:342:11)
04.07.17 12:04:04 (+1000)     at emitOne (events.js:96:13)
04.07.17 12:04:04 (+1000)     at Socket.emit (events.js:188:7)
04.07.17 12:04:04 (+1000)     at Pipe._handle.close [as _onclose] (net.js:497:12)
```

**Comment by nistath** [comment]
resin-cam has been reworked, so I suggest you use the [overhaul branch](https://github.com/resin-io-playground/resin-cam/tree/overhaul) until the new version of resin-cam is merged into master.
It doesn't yet include resin-wifi-connect, a small feature that lets you configure wifi after deploying a device, but assuming that you've set up your wifi settings when downloading the OS image, it should work fine even now.
When the new version of resin-wifi-connect is released we'll merge the new resin-cam into master.

If you clone this repo exactly, deploy to resin with `git push overhaul:master`.

**Comment by nistath** [comment]
The changes have been merged. Want to try again now?

**Comment by gdaybrice** [comment]
Thanks a lot for your help Nick! Will have a look again this weekend.
